version: '3.7'

services:
  db:
    image: mysql:8.0.29
    container_name: CloudAppDb
    environment:
      MYSQL_DATABASE: 'cloud-app-db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'zaq1@WSX'
      MYSQL_ROOT_PASSWORD: 'zaq1@WSX'
    ports:
      - '3306:3306'
    volumes:
      - ./docker-files/db:/var/lib/mysql
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  my-db:
