- name: Backend configuration
  hosts: backend
  become: true

  tasks:
    - name: Install Python and pip
      apt:
        name: [python3, python3-pip]
        state: present

    - name: Clone repository
      git:
        repo: https://github.com/karolkarolski25/CloudApplications.git
        dest: /home/vagrant/CloudApplications

    - name: Install Python requirements
      pip:
        requirements: /home/vagrant/CloudApplications/backend/requirements.txt
        state: present

    - name: Start python app
      command: python3 main.py
      args:
        chdir: /home/vagrant/CloudApplications/backend
      environment:
        DATABASE_LOCATION: 192.168.56.4
