version: '3.7'

services:
  db:
    image: mysql:8.0.29
    container_name: CloudAppDb
    environment:
      MYSQL_DATABASE: 'cloud-app-db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'zaq1@WSX'
      MYSQL_ROOT_PASSWORD: 'zaq1@WSX'
    ports:
      - '3306:3306'
    volumes:
      - ./docker-files/db:/var/lib/mysql
    networks:
      - cloudNet

  backend:
    container_name: CloudAppBackend
    build:
      dockerfile: Dockerfile.production
      context: "../../backend"
    ports:
      - 5000:5000
    environment:
      DATABASE_LOCATION: 'CloudAppDb'
    depends_on:
      - db
    networks:
      - cloudNet

  frontend:
    container_name: CloudAppFrontend
    stdin_open: true
    build:
      dockerfile: Dockerfile.production
      context: ../../web
    environment:
      REACT_APP_API_URL: 'http://localhost:5000'
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - cloudNet

volumes:
  my-db:

networks:
  cloudNet:
    ipam:
      driver: default
      